CREATE DATABASE galeria;
USE galeria;
CREATE TABLE persona (id INT PRIMARY KEY AUTO_INCREMENT NOT NULL, borrado boolean, nombre VARCHAR(30), segundoNombre VARCHAR(30), apellido VARCHAR(30), segundoApellido VARCHAR(30), documento VARCHAR(12), nacimiento DATE, sexo ENUM('f','m'), email VARCHAR(30));
CREATE TABLE telefono (id INT PRIMARY KEY AUTO_INCREMENT NOT NULL, borrado boolean, persona INT, pais INT, cArea INT, numero INT, FOREIGN KEY (persona) REFERENCES persona(id) ON DELETE CASCADE);
CREATE TABLE direccion (id INT PRIMARY KEY AUTO_INCREMENT NOT NULL, borrado boolean, persona INT, calle VARCHAR(30), numero INT, manzana VARCHAR(10), lote VARCHAR(10), edificio VARCHAR(10), piso INT, departamento VARCHAR(10), barrio VARCHAR(30), localidad VARCHAR(30), ciudad VARCHAR(30), provincia VARCHAR(30), pais VARCHAR(30), codigoPostal VARCHAR(10), FOREIGN KEY (persona) REFERENCES persona(id) ON DELETE CASCADE);
CREATE TABLE rubro (id INT PRIMARY KEY AUTO_INCREMENT NOT NULL, borrado boolean, rubro VARCHAR(30), descripcion VARCHAR(100));
CREATE TABLE inquilino (id INT PRIMARY KEY AUTO_INCREMENT NOT NULL, borrado boolean, persona INT, alta DATE, FOREIGN KEY (persona) REFERENCES persona(id) ON DELETE CASCADE);
CREATE TABLE espacio (id INT PRIMARY KEY AUTO_INCREMENT NOT NULL, borrado boolean, nombre VARCHAR(30), estado ENUM('libre','ocupado','reservado','mantenimiento'), ancho INT, largo INT, tipo VARCHAR(30), inquilino INT, precio DECIMAL(8,2), rubro INT, recargoUbicacion DECIMAL(3,2), descripcion VARCHAR(100), FOREIGN KEY (inquilino) REFERENCES inquilino(id) ON DELETE CASCADE, FOREIGN KEY (rubro) REFERENCES rubro(id) ON DELETE CASCADE);
CREATE TABLE documentacion (id INT PRIMARY KEY AUTO_INCREMENT NOT NULL, borrado boolean, documento VARCHAR(255), inquilino INT, descripcion VARCHAR(100), emision DATE, vencimiento DATE, fechaPresentacion DATE, FOREIGN KEY (inquilino) REFERENCES inquilino(id) ON DELETE CASCADE);
CREATE TABLE archivo (id INT PRIMARY KEY AUTO_INCREMENT NOT NULL, borrado boolean, documentacion INT, archivo VARCHAR(20), url VARCHAR(255), FOREIGN KEY (documentacion) REFERENCES documentacion(id) ON DELETE CASCADE);
CREATE TABLE contrato (id INT PRIMARY KEY AUTO_INCREMENT NOT NULL, borrado boolean, registro DATETIME, fecha DATETIME, condiciones VARCHAR(10000), inquilino INT, espacio INT, inicio DATETIME, fin DATETIME, nota VARCHAR(400), FOREIGN KEY (inquilino) REFERENCES inquilino(id) ON DELETE CASCADE, FOREIGN KEY (espacio) REFERENCES espacio(id) ON DELETE CASCADE);
CREATE TABLE rol (id INT PRIMARY KEY AUTO_INCREMENT NOT NULL, borrado boolean, rol VARCHAR(30), descripcion VARCHAR(400), nota VARCHAR(400));
CREATE TABLE usuario (id INT PRIMARY KEY AUTO_INCREMENT, borrado boolean, usuario VARCHAR(30), clave VARCHAR(100), persona INT, rol INT, estado ENUM('activo','inactivo'), creacion DATE, ultimoAcceso DATE, FOREIGN KEY (persona) REFERENCES persona(id) ON DELETE CASCADE, FOREIGN KEY (rol) REFERENCES rol(id) ON DELETE CASCADE);
CREATE TABLE pago (id INT PRIMARY KEY AUTO_INCREMENT NOT NULL, borrado boolean, registro DATETIME, usuario INT, numero INT, fecha DATETIME, inquilino INT, nota VARCHAR(400), FOREIGN KEY (usuario) REFERENCES usuario(id) ON DELETE CASCADE, FOREIGN KEY (inquilino) REFERENCES inquilino(id) ON DELETE CASCADE);
CREATE TABLE factura (id INT PRIMARY KEY AUTO_INCREMENT NOT NULL, borrado boolean, registro DATETIME, fecha DATETIME, numero INT, pago INT, estado ENUM('emitida','pagada'), nota VARCHAR(400), FOREIGN KEY (pago) REFERENCES pago(id) ON DELETE CASCADE);
CREATE TABLE servicio (id INT PRIMARY KEY AUTO_INCREMENT NOT NULL, borrado boolean, servicio VARCHAR(30), cantidad INT, precio DECIMAL(10,2), factura INT, nota VARCHAR(400), FOREIGN KEY (factura) REFERENCES factura(id) ON DELETE CASCADE);
CREATE TABLE alquiler (id INT PRIMARY KEY AUTO_INCREMENT NOT NULL, borrado boolean, contrato INT, espacio INT, inicio DATETIME, fin DATETIME, estado ENUM('activo','inactivo'), nota VARCHAR(400), FOREIGN KEY (contrato) REFERENCES contrato(id) ON DELETE CASCADE, FOREIGN KEY (espacio) REFERENCES espacio(id) ON DELETE CASCADE);
CREATE TABLE reserva (id INT PRIMARY KEY AUTO_INCREMENT NOT NULL, borrado boolean, fecha DATE, espacio INT, inquilino INT, tipo VARCHAR(30), diaInicio DATE, diaFin DATE, inicio TIME, fin TIME, actividad VARCHAR(30), adelanto DECIMAL(10,2), estado ENUM('pagado','adeudado'), nota VARCHAR(400), FOREIGN KEY (espacio) REFERENCES espacio(id) ON DELETE CASCADE, FOREIGN KEY (inquilino) REFERENCES inquilino(id) ON DELETE CASCADE);
CREATE TABLE itemPago (id INT PRIMARY KEY AUTO_INCREMENT NOT NULL, borrado boolean, item VARCHAR(30), descripcion VARCHAR(200), cantidad INT, precio DECIMAL(10,2), monto DECIMAL(10,2), nota VARCHAR(200), pago INT, FOREIGN KEY (pago) REFERENCES pago(id) ON DELETE CASCADE);
CREATE TABLE permiso (id INT AUTO_INCREMENT PRIMARY KEY, borrado boolean, rol INT NOT NULL, recurso VARCHAR(100) NOT NULL, accion ENUM('agregar','editar','eliminar','ver') NOT NULL, permitido BOOLEAN NOT NULL DEFAULT FALSE, CONSTRAINT fk_permiso_rol FOREIGN KEY (rol) REFERENCES rol(id) ON DELETE CASCADE);
CREATE TABLE logMovimiento (id int auto_increment primary key, usuario int not null, accion enum('consulta','alta','baja','actualizacion') not null, entidad varchar(30) not null, campo text, previo text, nuevo text, fecha timestamp default current_timestamp, ip varchar(45), detalle text, foreign key (usuario) references usuario(id));
INSERT INTO persona (nombre, apellido) VALUES ('NombreAdm', 'ApellidoAdm');
INSERT INTO rol (rol, descripcion, nota) VALUES ('Super Administrador', 'Rol con todos los privilegios del sistema', 'Acceso total a todas las funciones');
INSERT INTO usuario (usuario, clave, persona, rol) VALUES ('admin', '$2b$10$JK6oWP3uwTvcov3e.zCE7ePSHKdaSykHOPt3paeK6qCCKWB5YtYO.', 1, 1);
INSERT INTO permiso (rol, recurso, accion, permitido) VALUES (1, 'permiso', 'ver', 1);
INSERT INTO permiso (rol, recurso, accion, permitido) VALUES (1, 'permiso', 'editar', 1);
INSERT INTO permiso (rol, recurso, accion, permitido) VALUES (1, 'permiso', 'eliminar', 1);
INSERT INTO permiso (rol, recurso, accion, permitido) VALUES (1, 'permiso', 'agregar', 1);
INSERT INTO permiso (rol, recurso, accion, permitido) VALUES (1, 'persona', 'ver', 1);
INSERT INTO permiso (rol, recurso, accion, permitido) VALUES (1, 'persona', 'editar', 1);
INSERT INTO permiso (rol, recurso, accion, permitido) VALUES (1, 'persona', 'eliminar', 1);
INSERT INTO permiso (rol, recurso, accion, permitido) VALUES (1, 'persona', 'agregar', 1);
INSERT INTO permiso (rol, recurso, accion, permitido) VALUES (1, 'direccion', 'ver', 1);
INSERT INTO permiso (rol, recurso, accion, permitido) VALUES (1, 'direccion', 'editar', 1);
INSERT INTO permiso (rol, recurso, accion, permitido) VALUES (1, 'direccion', 'eliminar', 1);
INSERT INTO permiso (rol, recurso, accion, permitido) VALUES (1, 'direccion', 'agregar', 1);
INSERT INTO permiso (rol, recurso, accion, permitido) VALUES (1, 'telefono', 'ver', 1);
INSERT INTO permiso (rol, recurso, accion, permitido) VALUES (1, 'telefono', 'editar', 1);
INSERT INTO permiso (rol, recurso, accion, permitido) VALUES (1, 'telefono', 'eliminar', 1);
INSERT INTO permiso (rol, recurso, accion, permitido) VALUES (1, 'telefono', 'agregar', 1);